### ISSUE TITLE
[Bug Report] Turtle doesn't return to start location (+1.12)

### ISSUE THREAD

**Issue by 1m1w1j1** [HeshamSHY/Turtly-Farmer#1] opened 2022-03-14 22:05 UTC
I'm using Minecraft 1.18 with the All The Mods 7 modpack.

On the very last column of the farm the turtle doesn't turn around.
Instead it goes forward until it runs into a block. 

@HeshamSHY

**Comment by HeshamSHY** [comment] 2022-03-17 06:10
Can you please send a video or pictures of what's happening

**Comment by HeshamSHY** [comment] 2022-03-19 07:52
ig I know what the issue is now, so I'm going to try to fix it, if you are able to provide a couple of screenshots or a video it would help identify what the issue is exactly.

**Comment by 1m1w1j1** [comment] 2022-04-09 01:39
I just saw this. I will try to make a video as soon as I can.

**Comment by tildedrage** [comment] 2022-04-13 23:06
hi, im also having this problem

**Comment by tmahring** [comment] 2023-02-14 09:15
Ran into the same problem.
Seems the name for the fence block got changed to minecraft:oka_fence at some point.
changing all 3 occurances in tutlyfarmer.lua fixes the issue, tested in 1.19.3
Changed it ingame, so no pull-request ;)

**Comment by tmahring** [comment] 2023-02-14 09:35
also in line 85 insBlock.metadata need to be changed to insBlock.state.age in order for harvesting to work in 1.19.3

**Comment by laxfan20** [comment] 2023-04-05 23:44
I am also having this issue, playing on All of Fabric 5 Minecraft version 1.18.2, the turtle just drives off after the last farm plot and doesn't stop until it hits a block. Any fixes or changes in the code I need to make?

**Comment by HeshamSHY** [comment] 2023-04-06 05:05
Well, Hi everyone
I'm going to roll out a fix for this today hopfully
I'm going to add a new version for 1.13+

**Comment by HeshamSHY** [comment] 2023-04-06 20:26
Fixed in [commit `5c60694`](https://github.com/HeshamSHY/Turtly-Farmer/commit/5c606940d035439dca951663699157bf161238be)

I added another version for 1.18 update(which should work with 1.13+)

**Closed as completed by HeshamSHY** 2023-04-06 20:26 UTC
Labels: good first issue
